# sources.py — Base monstruosa de fontes de notícias ESG (500+ fontes)

ESG_CATEGORIES = {
    "Meio Ambiente": [
        "carbono", "emissão", "clima", "aquecimento global", "desmatamento",
        "biodiversidade", "poluição", "energia renovável", "reciclagem",
        "sustentabilidade ambiental", "queimada", "lixo", "resíduo", "net zero",
        "metano", "eólica", "solar", "hidrogênio verde", "compensação ambiental",
        "derramamento", "contaminação", "bioma", "cerrado", "amazônia",
    ],
    "Social": [
        "trabalhador", "acidente de trabalho", "diversidade", "inclusão",
        "direitos humanos", "trabalho infantil", "trabalho escravo", "saúde",
        "comunidade", "gênero", "racial", "equidade", "bem-estar",
        "assédio", "demissão em massa", "greve", "salário mínimo", "discriminação",
    ],
    "Governança": [
        "corrupção", "compliance", "transparência", "auditoria", "ética",
        "conselho", "fraude", "bribery", "lavagem de dinheiro", "conflito de interesse",
        "leniência", "caixa dois", "desvio", "anticorrupção", "governança corporativa",
        "código de conduta", "insider trading", "delação",
    ],
    "Risco": [
        "multa", "embargo", "investigação", "processo judicial", "denúncia",
        "infração", "vazamento", "acidente", "desastre", "crise", "escândalo",
        "suspensão", "autuação", "ibama", "procon", "anvisa", "recall",
        "interdição", "penalidade", "enforcement", "CVM", "SEC",
    ],
    "Positivo": [
        "premiação esg", "certificação", "relatório de sustentabilidade",
        "carbono neutro", "net zero", "índice de sustentabilidade",
        "green bond", "título verde", "b corp", "gri", "impacto positivo",
        "responsabilidade social", "economia circular",
    ],
}

NEWS_SOURCES = {

    # ── Brasil · Grandes Veículos ──────────────────────────────────────────────
    "🇧🇷 Brasil — Grandes Veículos": [
        "Folha de S.Paulo (folha.uol.com.br)",
        "O Globo (oglobo.globo.com)",
        "Estadão (estadao.com.br)",
        "UOL Notícias (noticias.uol.com.br)",
        "G1 (g1.globo.com)",
        "CNN Brasil (cnnbrasil.com.br)",
        "R7 (r7.com)",
        "Terra (terra.com.br)",
        "Metrópoles (metropoles.com)",
        "Correio Braziliense (correiobraziliense.com.br)",
        "O Tempo (otempo.com.br)",
        "A Tarde (atarde.com.br)",
        "Diário de Pernambuco (diariodepernambuco.com.br)",
        "Gazeta do Povo (gazetadopovo.com.br)",
        "Zero Hora (gauchazh.clicrbs.com.br)",
        "O Dia (odia.com.br)",
        "Band News (bandnewsfm.com.br)",
        "GZH (gzh.clicrbs.com.br)",
        "Jornal do Comércio (jc.ne10.uol.com.br)",
        "A Gazeta ES (gazetaonline.com.br)",
        "O Liberal PA (oliberal.com)",
        "Diário do Nordeste (diariodonordeste.com.br)",
        "Tribuna do Norte (tribunadonorte.com.br)",
        "Jornal da Cidade Bauru (jcnet.com.br)",
        "Gazeta de Alagoas (gazetaweb.com)",
        "A Crítica AM (acritica.com)",
        "Diário da Amazônia (diariodaamazonia.com.br)",
        "Portal AZ (portalamazonia.com)",
        "O Imparcial MA (oimparcial.com.br)",
        "Diário do Pará (diariodopara.com.br)",
    ],

    # ── Brasil · Negócios & Finanças ───────────────────────────────────────────
    "🇧🇷 Brasil — Negócios & Finanças": [
        "Valor Econômico (valor.com.br)",
        "InfoMoney (infomoney.com.br)",
        "Exame (exame.com)",
        "Bloomberg Línea Brasil (bloomberglinea.com.br)",
        "The Brazilian Report (brazilian.report)",
        "Poder360 (poder360.com.br)",
        "NeoFeed (neofeed.com.br)",
        "IstoÉ Dinheiro (istoedinheiro.com.br)",
        "Veja Negócios (veja.abril.com.br)",
        "Mercado & Consumo (mercadoeconsumo.com.br)",
        "Monitor do Mercado (monitormercado.com.br)",
        "Agência Estado (estadao.com.br/economia)",
        "Capital Aberto (capitalaberto.com.br)",
        "Brazil Journal (braziljournal.com)",
        "Suno Research (suno.com.br)",
        "Empiricus (empiricus.com.br)",
        "Seu Dinheiro (seudinheiro.com)",
        "Invest News (investnews.com.br)",
        "Money Times (moneytimes.com.br)",
        "Inteligência Financeira (inteligenciafinanceira.com.br)",
        "Stock Market BR (stockmarket.br)",
        "TradeMap (trademap.com.br)",
        "Pipeline (pipelinevalor.com.br)",
        "Startups (startups.com.br)",
        "Pequenas Empresas & Grandes Negócios (revistapegn.globo.com)",
        "Veja (veja.abril.com.br)",
        "Época Negócios (epocanegocios.globo.com)",
        "PEGN (revistapegn.globo.com)",
        "Economia SC (economia.sc.gov.br)",
        "Jornal de Negócios (jornaldenegocios.pt)",
    ],

    # ── Brasil · ESG & Sustentabilidade ───────────────────────────────────────
    "🇧🇷 Brasil — ESG & Sustentabilidade": [
        "Envolverde (envolverde.com.br)",
        "Planeta Sustentável (planetasustentavel.com.br)",
        "ESG Insights (esginsights.com.br)",
        "Exame ESG (exame.com/esg)",
        "Valor Econômico ESG (valor.com.br/esg)",
        "IstoÉ Sustentabilidade (istoe.com.br)",
        "Carbono Brasil (carbonobrasil.com)",
        "Amazônia Real (amazoniareal.com.br)",
        "InfoAmazônia (infoamazonia.org)",
        "((o))eco (oeco.org.br)",
        "Mongabay Brasil (brasil.mongabay.com)",
        "Nexo Jornal (nexojornal.com.br)",
        "Agência Pública (apublica.org)",
        "Agência FAPESP (agencia.fapesp.br)",
        "Observatório do Clima (observatoriodoclima.eco.br)",
        "Brasil de Fato (brasildefato.com.br)",
        "Diálogo Chino Brasil (dialogochino.net/pt)",
        "Repórter Brasil (reporterbrasil.org.br)",
        "Agência Imazon (imazon.org.br)",
        "Projeto Mapbiomas (mapbiomas.org)",
        "GovES (cidades.ibge.gov.br)",
        "ESGo (esgo.com.br)",
        "Sustainable Business BR (sustainablebusiness.com.br)",
        "CEBDS (cebds.org)",
        "Instituto Ethos (ethos.org.br)",
        "Akatu (akatu.net.br)",
        "WWF Brasil (wwf.org.br)",
        "Greenpeace Brasil (greenpeace.org/brasil)",
        "SOS Mata Atlântica (sosma.org.br)",
        "Fundação Brasileira para o Desenvolvimento Sustentável (fbds.org.br)",
        "Instituto Clima e Sociedade (climaesociedade.org)",
        "Conexão Planeta (conexaoplaneta.com.br)",
        "Fórum Econômico Mundial BR (weforum.org)",
        "ESGHub (esghub.com.br)",
        "RI Mais (rimais.com.br)",
    ],

    # ── Brasil · Agronegócio ───────────────────────────────────────────────────
    "🇧🇷 Brasil — Agronegócio": [
        "Agrolink (agrolink.com.br)",
        "Notícias Agrícolas (noticiasagricolas.com.br)",
        "Canal Rural (canalrural.com.br)",
        "Globo Rural (globorural.globo.com)",
        "CNA Brasil (cnabrasil.org.br)",
        "AgroFoco (agrofoco.com.br)",
        "AgroMais (agromais.com.br)",
        "Embrapa (embrapa.br)",
        "Safras & Mercado (safras.com.br)",
        "Agrofy News (news.agrofy.com.br)",
        "Terra Viva (terraviva.com.br)",
        "Agricultura (agricultura.gov.br)",
        "Valor do Campo (valordocampo.com.br)",
        "Soja & Cia (sojaecia.com.br)",
        "Pecuária Brasil (pecuariabrasil.com.br)",
        "AgriBrasil (agribrasil.agr.br)",
        "Canal do Produtor (canaldoprodutor.com.br)",
        "Rural Centro (ruralcentro.com.br)",
    ],

    # ── Brasil · Energia ───────────────────────────────────────────────────────
    "🇧🇷 Brasil — Energia & Clima": [
        "Canal Energia (canalenergia.com.br)",
        "Energia Hoje (energiahoje.com)",
        "Portal PCH (portalpchnoticias.com.br)",
        "EDP Notícias (edp.com.br)",
        "Aneel (aneel.gov.br)",
        "EPE (epe.gov.br)",
        "ONS (ons.org.br)",
        "Canaltech Energia (canaltech.com.br/energia)",
        "Jornal de Energia (jornaldeenergia.com.br)",
        "GE Brasil (ge.com/br)",
        "Siemens Energy BR (siemens-energy.com/br)",
        "Solar Power World (solarpowerworldonline.com)",
        "Wind Energy Update (windenergyupdate.com)",
        "ReNovaBR (renovabr.org)",
    ],

    # ── Brasil · Mineração & Óleo e Gás ───────────────────────────────────────
    "🇧🇷 Brasil — Mineração & Óleo e Gás": [
        "Minérios & Minerales (minerioseminerales.com.br)",
        "AngloAmerican News (angloamerican.com/media)",
        "Vale Notícias (vale.com/noticias)",
        "Petrobras Fatos e Dados (petrobras.com.br/fatos-e-dados)",
        "IBP (ibp.org.br)",
        "ANP (gov.br/anp)",
        "DNPM / ANM (anm.gov.br)",
        "Portal do Minério (portaldomineiro.com.br)",
        "Brasil Mineral (brasileiromineral.com.br)",
        "OilandGas (oilandgas.com.br)",
        "Offshore Technology (offshore-technology.com)",
        "Platts Energy (platts.com)",
    ],

    # ── Brasil · Jurídico & Regulatório ───────────────────────────────────────
    "🇧🇷 Brasil — Jurídico & Regulatório": [
        "Consultor Jurídico (conjur.com.br)",
        "Migalhas (migalhas.com.br)",
        "Jota (jota.info)",
        "Compliance Total (compliancetotal.com.br)",
        "Agência Senado (agencia.senado.leg.br)",
        "TCU (tcu.gov.br)",
        "IBAMA (ibama.gov.br)",
        "MMA (gov.br/mma)",
        "CVM (cvm.gov.br)",
        "CADE (cade.gov.br)",
        "AGU (agu.gov.br)",
        "Receita Federal (gov.br/receitafederal)",
        "MPF (mpf.mp.br)",
        "Controladoria-Geral da União (cgu.gov.br)",
        "ANTT (antt.gov.br)",
        "ANVISA (anvisa.gov.br)",
        "BACEN (bcb.gov.br)",
        "Decreto Regulatório (decretoregulatorio.com.br)",
        "Direito Net (direitonet.com.br)",
        "LexML (lexml.gov.br)",
    ],

    # ── Brasil · Setorial & Industrial ────────────────────────────────────────
    "🇧🇷 Brasil — Setorial & Industrial": [
        "Petroquímica (petroquimica.com.br)",
        "Saneamento Ambiental (saneamentoambiental.com.br)",
        "Construção Mercado (construcaomercado.com.br)",
        "Logística Descomplicada (logisticadescomplicada.com)",
        "TI Inside (tiinside.com.br)",
        "Automotive Business (automotivebusiness.com.br)",
        "Super Varejo (supervarejo.com.br)",
        "Consumidor Moderno (consumidormoderno.com.br)",
        "Embalagem Marca (embalagem.negociosetecnologia.com.br)",
        "Farmacêutica (farmaceutica.com.br)",
        "FoodTech (foodtechbr.com)",
        "Química e Derivados (quimicaederivados.com.br)",
        "Cosméticos & Perfumaria (cosmeticoseperfumaria.com.br)",
        "Aço Brasil (acobrasil.org.br)",
        "CNI (portaldaindustria.com.br)",
        "FIESP (fiesp.com.br)",
        "ABNT (abnt.org.br)",
        "INMETRO (inmetro.gov.br)",
        "Inovação Industrial (inovacaoindustrial.com.br)",
        "Transporte Moderno (transportemoderno.com.br)",
    ],

    # ── Brasil · Saúde & Farmacêutico ─────────────────────────────────────────
    "🇧🇷 Brasil — Saúde & Farmacêutico": [
        "Saúde Business (saudebusiness.com.br)",
        "Medicina SA (medicinanet.com.br)",
        "Correio Farmacêutico (correiofarmaceutico.com.br)",
        "BioWorld (bioworld.com)",
        "CFM (cfm.org.br)",
        "CONASS (conass.org.br)",
        "Agência Saúde (saude.gov.br)",
        "Radis Fiocruz (radis.ensp.fiocruz.br)",
        "iSaúde (isaudebrasil.com.br)",
        "Saúde Plena (saudeplena.com)",
    ],

    # ── Internacional · Geral ─────────────────────────────────────────────────
    "🌍 Internacional — Geral": [
        "Reuters (reuters.com)",
        "Bloomberg (bloomberg.com)",
        "Financial Times (ft.com)",
        "The Wall Street Journal (wsj.com)",
        "Associated Press (apnews.com)",
        "BBC News (bbc.com/news)",
        "The Guardian (theguardian.com)",
        "The New York Times (nytimes.com)",
        "CNN International (edition.cnn.com)",
        "Al Jazeera (aljazeera.com)",
        "Deutsche Welle (dw.com)",
        "France 24 (france24.com)",
        "CNBC (cnbc.com)",
        "Forbes (forbes.com)",
        "Fortune (fortune.com)",
        "The Economist (economist.com)",
        "Time (time.com)",
        "Axios (axios.com)",
        "Politico (politico.com)",
        "The Independent (independent.co.uk)",
        "Le Monde (lemonde.fr)",
        "El País (elpais.com)",
        "Der Spiegel (spiegel.de)",
        "NHK World (nhk.or.jp/nhkworld)",
        "South China Morning Post (scmp.com)",
        "Nikkei Asia (asia.nikkei.com)",
        "The Hindu Business Line (thehindubusinessline.com)",
        "The Straits Times (straitstimes.com)",
        "Arab News (arabnews.com)",
        "Business Insider (businessinsider.com)",
        "MarketWatch (marketwatch.com)",
        "Yahoo Finance (finance.yahoo.com)",
        "Seeking Alpha (seekingalpha.com)",
        "Barron's (barrons.com)",
    ],

    # ── Internacional · ESG & Sustentabilidade ────────────────────────────────
    "🌍 Internacional — ESG & Sustentabilidade": [
        "ESG Today (esgtoday.com)",
        "GreenBiz (greenbiz.com)",
        "Responsible Investor (responsible-investor.com)",
        "Environmental Finance (environmental-finance.com)",
        "Carbon Brief (carbonbrief.org)",
        "Climate Home News (climatechangenews.com)",
        "BusinessGreen (businessgreen.com)",
        "Triple Pundit (triplepundit.com)",
        "Sustainable Brands (sustainablebrands.com)",
        "Corporate Knights (corporateknights.com)",
        "ESG Clarity (esgclarity.com)",
        "Impakter (impakter.com)",
        "Ethical Corporation (ethicalcorp.com)",
        "Bloomberg Green (bloomberg.com/green)",
        "Reuters Sustainability (reuters.com/sustainability)",
        "FT Moral Money (ft.com/moral-money)",
        "S&P Global ESG (spglobal.com/esg)",
        "Morningstar ESG (morningstar.com/lp/esg)",
        "ESG Investor (esginvestor.net)",
        "Institutional Investor ESG (institutionalinvestor.com)",
        "Chief Sustainability Officer (chief-sustainability-officer.com)",
        "Sustainability Magazine (sustainabilitymag.com)",
        "The Sustainability Report (sustainabilityreport.com)",
        "Impact Alpha (impactalpha.com)",
        "CleanTechnica (cleantechnica.com)",
        "RenewEconomy (reneweconomy.com.au)",
        "PV Magazine (pv-magazine.com)",
        "Wind Power Monthly (windpowermonthly.com)",
        "Energy Monitor (energymonitor.ai)",
        "Carbon Pulse (carbon-pulse.com)",
        "ENDS Report (endsreport.com)",
        "Resource (resource.co)",
        "edie (edie.net)",
        "Ethical Consumer (ethicalconsumer.org)",
        "Just Capital (justcapital.com)",
    ],

    # ── Internacional · Supply Chain & Trade ──────────────────────────────────
    "🌍 Internacional — Supply Chain & Compliance": [
        "Supply Chain Dive (supplychaindive.com)",
        "Logistics Management (logisticsmgmt.com)",
        "Supply Management (cips.org/supply-management)",
        "Global Trade Magazine (globaltrademag.com)",
        "Trade Finance Global (tradefinanceglobal.com)",
        "Compliance Week (complianceweek.com)",
        "Global Compliance News (globalcompliancenews.com)",
        "Anti-Corruption Digest (anti-corruptiondigest.com)",
        "TRACE International (traceinternational.org)",
        "FCPAméricas (fcpamericas.com)",
        "FCPA Blog (fcpablog.com)",
        "Supply Chain Brain (supplychainbrain.com)",
        "Freightwaves (freightwaves.com)",
        "The Loadstar (theloadstar.com)",
        "Lloyd's List (lloydslist.com)",
        "Journal of Commerce (joc.com)",
        "Sourcing Journal (sourcingjournal.com)",
        "Apparel Insider (apparelinsider.com)",
        "Know The Chain (knowthechain.org)",
        "Business & Human Rights Resource Centre (business-humanrights.org)",
    ],

    # ── Internacional · Finanças & Investimento ────────────────────────────────
    "🌍 Internacional — Finanças & Investimento": [
        "Institutional Investor (institutionalinvestor.com)",
        "Pensions & Investments (pionline.com)",
        "Citywire (citywire.com)",
        "Funds Europe (funds-europe.com)",
        "Investment Week (investmentweek.co.uk)",
        "Global Investor (globalinvestorgroup.com)",
        "Euromoney (euromoney.com)",
        "Risk.net (risk.net)",
        "The Banker (thebanker.com)",
        "Private Equity News (penews.com)",
        "Private Equity International (privateequityinternational.com)",
        "Preqin (preqin.com)",
        "Refinitiv (refinitiv.com)",
        "IPE Real Assets (ipe.com/real-assets)",
        "International Financing Review (ifre.com)",
        "Global Capital (globalcapital.com)",
        "FinanceAsia (financeasia.com)",
        "Emerging Markets (emergingmarkets.org)",
        "LatinFinance (latinfinance.com)",
    ],

    # ── América Latina ─────────────────────────────────────────────────────────
    "🌎 América Latina": [
        "América Economía (americaeconomia.com)",
        "El País América (elpais.com/america)",
        "Infobae (infobae.com)",
        "La Nación Argentina (lanacion.com.ar)",
        "El Comercio Perú (elcomercio.pe)",
        "El Espectador Colombia (elespectador.com)",
        "La República Colombia (larepublica.co)",
        "El Financiero México (elfinanciero.com.mx)",
        "Expansión México (expansion.mx)",
        "Bloomberg Línea (bloomberglinea.com)",
        "Diálogo Chino (dialogochino.net)",
        "Portafolio Colombia (portafolio.co)",
        "El Economista México (eleconomista.com.mx)",
        "El Mercurio Chile (emol.com)",
        "La Tercera Chile (latercera.com)",
        "Gestión Perú (gestion.pe)",
        "El Comercio Ecuador (elcomercio.com)",
        "La Prensa Panamá (prensa.com)",
        "El Tiempo Colombia (eltiempo.com)",
        "Semana Colombia (semana.com)",
        "Clarin Argentina (clarin.com)",
        "Ámbito Argentina (ambito.com)",
        "La Voz Argentina (lavoz.com.ar)",
        "ESG America Latina (esgamericalatina.com)",
        "Sustentabilidad AR (sustentabilidad.com.ar)",
    ],

    # ── Dados & Análise ESG ────────────────────────────────────────────────────
    "📊 Dados & Análise ESG": [
        "MSCI ESG (msci.com/esg-investing)",
        "Sustainalytics (sustainalytics.com)",
        "ISS ESG (issgovernance.com/esg)",
        "Vigeo Eiris (vigeo-eiris.com)",
        "CDP (cdp.net)",
        "GRI (globalreporting.org)",
        "SASB (sasb.org)",
        "UN Global Compact (unglobalcompact.org)",
        "World Resources Institute (wri.org)",
        "IPCC (ipcc.ch)",
        "Moody's ESG (moodys.com/esg)",
        "Fitch Ratings ESG (fitchratings.com)",
        "S&P Global Ratings ESG (spglobal.com/ratings)",
        "RepRisk (reprisk.com)",
        "TruValue Labs (truvaluelabs.com)",
        "Bloomberg ESG Data (bloomberg.com/professional/solution/esg)",
        "FactSet ESG (factset.com/solutions/esg)",
        "Refinitiv ESG Scores (refinitiv.com/en/financial-data/company-data/esg-scores)",
        "ISE B3 (b3.com.br/pt_br/produtos-e-servicos/indices/indices-de-sustentabilidade/ise)",
        "DJSI (spglobal.com/esg/indices/djsi-world)",
        "FTSE4Good (ftserussell.com/products/indices/FTSE4Good)",
        "Euronext Vigeo (euronext.com)",
        "EcoVadis (ecovadis.com)",
        "Sedex (sedex.com)",
        "BSR (bsr.org)",
        "AccountAbility (accountability.org)",
        "Climate Action 100+ (climateaction100.org)",
        "PRI (unpri.org)",
        "TCFD (tcfdhub.org)",
        "Science Based Targets (sciencebasedtargets.org)",
    ],

    # ── Reguladores & Órgãos Internacionais ───────────────────────────────────
    "🏛️ Reguladores & Órgãos Internacionais": [
        "SEC (sec.gov)",
        "ESMA (esma.europa.eu)",
        "FCA UK (fca.org.uk)",
        "BaFin Alemanha (bafin.de)",
        "AMF França (amf-france.org)",
        "IOSCO (iosco.org)",
        "OECD (oecd.org)",
        "World Bank (worldbank.org)",
        "IFC (ifc.org)",
        "IMF (imf.org)",
        "UNEP FI (unepfi.org)",
        "UNEP (unep.org)",
        "UNDP (undp.org)",
        "ILO (ilo.org)",
        "WTO (wto.org)",
        "FATF / GAFI (fatf-gafi.org)",
        "Transparency International (transparency.org)",
        "Basel Committee (bis.org)",
        "Network for Greening the Financial System (ngfs.net)",
        "International Energy Agency (iea.org)",
        "IRENA (irena.org)",
        "IASB / IFRS Foundation (ifrs.org)",
        "ISSB (ifrs.org/groups/international-sustainability-standards-board)",
    ],

    # ── Mídia Especializada Global ─────────────────────────────────────────────
    "📰 Mídia Especializada Global": [
        "Harvard Business Review (hbr.org)",
        "MIT Sloan Management Review (sloanreview.mit.edu)",
        "McKinsey Insights (mckinsey.com/insights)",
        "Deloitte Insights (deloitte.com/insights)",
        "PwC Insights (pwc.com/insights)",
        "EY Insights (ey.com/insights)",
        "KPMG Insights (kpmg.com/insights)",
        "BCG Insights (bcg.com/insights)",
        "Bain Insights (bain.com/insights)",
        "World Economic Forum (weforum.org)",
        "Project Syndicate (project-syndicate.org)",
        "Chatham House (chathamhouse.org)",
        "Brookings (brookings.edu)",
        "CSIS (csis.org)",
        "Milken Institute (milkeninstitute.org)",
        "Davos Agenda (weforum.org/agenda)",
        "Stanford Social Innovation Review (ssir.org)",
        "Nature (nature.com)",
        "Science (sciencemag.org)",
        "The Lancet (thelancet.com)",
        "Vox (vox.com)",
        "Quartz (qz.com)",
        "Rest of World (restofworld.org)",
        "The Wire (thewire.in)",
        "New Statesman (newstatesman.com)",
        "Prospect Magazine (prospectmagazine.co.uk)",
    ],

    # ── África & Oriente Médio ─────────────────────────────────────────────────
    "🌍 África & Oriente Médio": [
        "Business Day Nigeria (businessday.ng)",
        "The East African (theeastafrican.co.ke)",
        "Daily Maverick SA (dailymaverick.co.za)",
        "Business Report SA (iol.co.za/business-report)",
        "African Business (african.business)",
        "ESG Africa (esgafrica.com)",
        "This Is Africa (thisisafrica.me)",
        "Arab News (arabnews.com)",
        "Gulf News (gulfnews.com)",
        "Al Monitor (al-monitor.com)",
        "The National UAE (thenationalnews.com)",
        "Middle East Eye (middleeasteye.net)",
        "MEED (meed.com)",
        "Zawya (zawya.com)",
    ],

    # ── Ásia & Oceania ─────────────────────────────────────────────────────────
    "🌏 Ásia & Oceania": [
        "Nikkei Asia (asia.nikkei.com)",
        "South China Morning Post (scmp.com)",
        "The Straits Times (straitstimes.com)",
        "Economic Times India (economictimes.indiatimes.com)",
        "Mint India (livemint.com)",
        "Business Standard India (business-standard.com)",
        "Caixin Global (caixinglobal.com)",
        "Sixth Tone China (sixthtone.com)",
        "Korea Herald (koreaherald.com)",
        "Bangkok Post (bangkokpost.com)",
        "The Australian (theaustralian.com.au)",
        "AFR Australia (afr.com)",
        "RenewEconomy Australia (reneweconomy.com.au)",
        "Asia Sentinel (asiasentinel.com)",
        "ESG Asia (esginvestor.net/region/asia)",
        "AsianInvestor (asianinvestor.net)",
    ],

    # ── Europa ─────────────────────────────────────────────────────────────────
    "🇪🇺 Europa": [
        "Politico EU (politico.eu)",
        "Euractiv (euractiv.com)",
        "The Local (thelocal.eu)",
        "EurActiv ESG (euractiv.com/section/energy-environment)",
        "Les Echos (lesechos.fr)",
        "Handelsblatt (handelsblatt.com)",
        "Corriere della Sera (corriere.it)",
        "Il Sole 24 Ore (ilsole24ore.com)",
        "El Economista España (eleconomista.es)",
        "Expansion España (expansion.com)",
        "De Telegraaf (telegraaf.nl)",
        "NRC Handelsblad (nrc.nl)",
        "Dagens Næringsliv (dn.no)",
        "Aftenposten (aftenposten.no)",
        "Helsingin Sanomat (hs.fi)",
        "Dagens Nyheter (dn.se)",
        "Die Welt (welt.de)",
        "Frankfurter Allgemeine (faz.net)",
        "Sustainability Europe (sustainability-europe.com)",
    ],

    # ── Investigação & Transparência ──────────────────────────────────────────
    "🔍 Investigação & Transparência": [
        "ICIJ (icij.org)",
        "OCCRP (occrp.org)",
        "ProPublica (propublica.org)",
        "The Intercept (theintercept.com)",
        "The Intercept Brasil (theintercept.com/brasil)",
        "Agência Pública BR (apublica.org)",
        "Transparência Internacional (transparency.org)",
        "Global Witness (globalwitness.org)",
        "Partnership on AI (partnershiponai.org)",
        "Conectas (conectas.org)",
        "Inesc (inesc.org.br)",
        "Ibase (ibase.br)",
        "Article 19 (article19.org)",
        "Access Now (accessnow.org)",
        "Global Financial Integrity (gfintegrity.org)",
        "TI Brasil (transparencia.org.br)",
        "Fiquem Sabendo (fiquemsabendo.com.br)",
        "Agência Lupa (lupa.news)",
        "Aos Fatos (aosfatos.org)",
    ],
}
